In [165]:
import pandas as pd

In [166]:
df = pd.read_csv("Data/RegionalInterestByConditionOverTime.csv")
df.head()

,dma,geoCode,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea,2004+obesity,...,2016+diabetes,2017+cancer,2017+cardiovascular,2017+stroke,2017+depression,2017+rehab,2017+vaccine,2017+diarrhea,2017+obesity,2017+diabetes
0,Portland-Auburn ME,500,44,6,17,39,21,31,14,29,...,81,70,37,83,64,56,76,66,47,80
1,New York NY,501,47,6,13,38,16,33,12,27,...,77,70,34,53,56,53,79,56,52,78
2,Binghamton NY,502,48,3,16,50,12,37,24,31,...,74,68,24,71,69,44,77,78,61,72
3,Macon GA,503,44,14,14,37,19,49,14,29,...,78,53,38,62,46,60,47,53,41,66
4,Philadelphia PA,504,52,7,16,41,23,36,14,30,...,80,75,35,61,62,75,84,69,56,78

In [168]:
df =df.rename(columns = {'dma':'City & State'})

In [169]:
df.head()

,City & State,geoCode,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea,2004+obesity,...,2016+diabetes,2017+cancer,2017+cardiovascular,2017+stroke,2017+depression,2017+rehab,2017+vaccine,2017+diarrhea,2017+obesity,2017+diabetes
0,Portland-Auburn ME,500,44,6,17,39,21,31,14,29,...,81,70,37,83,64,56,76,66,47,80
1,New York NY,501,47,6,13,38,16,33,12,27,...,77,70,34,53,56,53,79,56,52,78
2,Binghamton NY,502,48,3,16,50,12,37,24,31,...,74,68,24,71,69,44,77,78,61,72
3,Macon GA,503,44,14,14,37,19,49,14,29,...,78,53,38,62,46,60,47,53,41,66
4,Philadelphia PA,504,52,7,16,41,23,36,14,30,...,80,75,35,61,62,75,84,69,56,78

In [170]:
df.drop(columns=['geoCode'])

,City & State,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea,2004+obesity,2004+diabetes,...,2016+diabetes,2017+cancer,2017+cardiovascular,2017+stroke,2017+depression,2017+rehab,2017+vaccine,2017+diarrhea,2017+obesity,2017+diabetes
0,Portland-Auburn ME,44,6,17,39,21,31,14,29,38,...,81,70,37,83,64,56,76,66,47,80
1,New York NY,47,6,13,38,16,33,12,27,32,...,77,70,34,53,56,53,79,56,52,78
2,Binghamton NY,48,3,16,50,12,37,24,31,37,...,74,68,24,71,69,44,77,78,61,72
3,Macon GA,44,14,14,37,19,49,14,29,31,...,78,53,38,62,46,60,47,53,41,66
4,Philadelphia PA,52,7,16,41,23,36,14,30,37,...,80,75,35,61,62,75,84,69,56,78
5,Detroit MI,47,6,16,45,14,31,15,27,34,...,73,69,38,66,61,57,73,70,45,74
6,Boston MA-Manchester NH,48,6,15,38,25,34,14,27,37,...,76,70,37,58,62,72,76,58,58,74
7,Savannah GA,43,11,17,37,28,43,10,45,26,...,70,63,32,71,60,47,66,70,44,74
8,Pittsburgh PA,51,10,17,50,23,34,16,35,43,...,79,73,35,73,65,72,86,79,52,79
9,Ft. Wayne IN,42,4,14,50,15,25,15,25,36,...,84,66,36,67,69,43,62,73,49,81
10,Cleveland-Akron (Canton) OH,42,6,16,44,18,26,14,25,36,...,77,70,35,65,64,52,71,73,51,75
11,Washington DC (Hagerstown MD),47,5,15,33,15,46,11,31,37,...,77,63,31,54,54,43,79,55,59,73
12,Baltimore MD,51,9,18,44,18,44,16,29,40,...,86,68,42,65,60,56,79,66,67,85
13,Flint-Saginaw-Bay City MI,43,8,17,50,12,34,19,48,31,...,77,69,47,79,72,54,76,76,63,76
14,Buffalo NY,49,5,20,49,18,25,16,26,37,...,78,72,32,65,66,61,70,74,52,76
15,Cincinnati OH,45,6,18,43,17,25,15,28,39,...,76,65,30,62,62,48,74,74,49,74
16,Erie PA,53,14,17,50,25,43,8,53,44,...,80,69,34,73,72,60,85,75,57,83
17,Charlotte NC,43,7,16,39,21,29,16,25,35,...,72,61,30,64,56,50,63,65,47,71
18,Greensboro-High Point-Winston Salem NC,47,10,15,45,24,29,13,32,37,...,80,68,39,71,60,68,70,69,52,80
19,Charleston SC,55,14,20,42,16,23,15,15,42,...,76,67,35,76,58,46,76,69,45,75
20,Augusta GA,48,12,26,39,18,24,14,33,37,...,79,68,50,75,61,58,67,69,61,79
21,Providence RI-New Bedford MA,43,3,16,45,20,36,17,20,32,...,77,65,40,59,63,55,77,68,48,74
22,Columbus GA,41,7,17,46,25,33,14,64,39,...,80,65,50,74,61,56,63,68,62,83
23,Burlington VT-Plattsburgh NY,49,6,14,53,21,44,10,43,38,...,72,68,30,75,72,63,90,68,59,68
24,Atlanta GA,42,6,15,35,19,36,13,23,36,...,73,64,37,62,54,48,65,65,48,72
25,Albany GA,44,5,12,43,27,24,16,18,46,...,79,63,50,69,62,52,54,73,47,81
26,Utica NY,42,19,19,63,31,100,19,49,29,...,83,68,33,70,66,51,73,81,58,80
27,Indianapolis IN,49,10,17,47,16,31,15,38,45,...,85,69,39,63,66,49,78,74,58,82
28,Miami-Ft. Lauderdale FL,37,7,11,29,17,28,7,20,34,...,70,61,40,53,45,47,60,46,49,70
29,Louisville KY,49,5,13,42,25,15,11,43,39,...,84,72,39,74,61,82,74,77,52,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,Rapid City SD,41,0,15,72,14,55,18,20,40,...,78,59,27,70,59,55,69,66,64,74
181,El Paso TX,43,5,13,43,8,28,7,51,46,...,94,59,52,53,67,39,70,66,53,82
182,Helena MT,36,16,19,52,17,0,36,28,67,...,97,67,10,75,64,58,91,69,46,93
183,Casper-Riverton WY,45,0,17,42,21,27,46,60,37,...,87,59,27,93,66,42,70,75,45,80
184,Salt Lake City UT,42,6,16,39,16,21,14,35,39,...,79,55,31,68,66,50,68,69,54,75
185,Yuma AZ-El Centro CA,36,0,23,45,19,54,0,27,31,...,75,57,57,55,60,36,65,71,48,80
186,Grand Junction-Montrose CO,39,11,8,57,14,26,45,57,28,...,76,57,19,74,61,43,68,66,56,72
187,Tucson (Sierra Vista) AZ,41,5,18,34,15,32,18,24,38,...,83,65,27,64,63,49,78,73,55,79
188,Albuquerque-Santa Fe NM,43,6,13,44,13,30,13,32,45,...,83,61,29,65,64,45,71,68,49,80
189,Glendive MT,43,0,0,0,0,0,0,0,0,...,0,58,0,0,0,0,0,0,0,0
190,Bakersfield CA,38,5,14,58,10,28,20,35,41,...,79,59,44,58,60,26,61,77,51,78
191,Eugene OR,41,9,19,44,15,42,11,39,40,...,78,61,31,75,59,40,80,65,86,79
192,Eureka CA,33,0,13,49,25,49,17,0,23,...,64,61,35,76,67,43,84,61,47,66
193,Los Angeles CA,37,5,15,33,16,25,11,24,30,...,73,59,33,55,58,37,65,61,53,74
194,Palm Springs CA,43,13,14,40,49,55,23,23,13,...,76,64,27,70,52,40,56,78,47,81
195,San Francisco-Oakland-San Jose CA,41,5,15,32,13,28,13,20,31,...,68,56,29,53,52,28,69,50,45,67
196,Yakima-Pasco-Richland-Kennewick WA,44,2,14,37,6,27,9,30,32,...,82,58,25,60,62,34,78,72,48,80
197,Reno NV,38,5,17,32,15,29,8,21,34,...,70,59,30,69,60,43,74,68,54,69
198,Medford-Klamath Falls OR,38,12,19,27,13,35,14,41,28,...,77,64,23,77,63,40,76,66,40,79
199,Seattle-Tacoma WA,42,4,15,39,15,32,13,26,33,...,72,57,22,63,56,42,80,63,46,71
200,Portland OR,38,4,18,40,15,25,14,29,36,...,75,56,31,62,58,44,67,59,58,73
201,Bend OR,53,12,18,48,14,55,12,46,45,...,61,60,26,81,59,39,77,55,50,61
202,San Diego CA,42,5,15,31,14,29,11,22,29,...,77,61,37,57,59,37,80,61,56,76
203,Monterey-Salinas CA,38,4,12,44,11,29,12,26,32,...,70,57,27,55,66,28,72,51,64,67
204,Las Vegas NV,33,4,16,32,16,22,16,17,30,...,69,59,31,55,52,52,60,65,42,70
205,Santa Barbara-Santa Maria-San Luis Obispo CA,35,5,13,40,14,30,9,38,27,...,63,53,24,60,59,28,76,56,53,63
206,Sacramento-Stockton-Modesto CA,40,4,17,41,12,35,13,29,35,...,75,59,29,64,55,36,75,66,55,76
207,Fresno-Visalia CA,34,7,13,48,16,19,5,33,34,...,81,56,42,61,68,36,61,73,63,77
208,Chico-Redding CA,36,4,22,33,16,49,14,41,24,...,75,58,38,76,63,59,89,70,62,75
209,Spokane WA,44,6,17,49,16,34,10,30,46,...,79,63,33,77,61,43,85,75,53,73

In [171]:
city = df["City & State"]

In [172]:
df_2004 = df.filter(like='2004')

In [173]:
df_2004.head()

,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea,2004+obesity,2004+diabetes
0,44,6,17,39,21,31,14,29,38
1,47,6,13,38,16,33,12,27,32
2,48,3,16,50,12,37,24,31,37
3,44,14,14,37,19,49,14,29,31
4,52,7,16,41,23,36,14,30,37

In [174]:
df_2004.columns = df_2004.columns.str.replace('2004+','')

In [175]:
df_2004.columns = df_2004.columns.str.replace('+','')

In [176]:
df_2004 = pd.concat([city,df_2004],axis=1)

In [177]:
df_2004['year'] = 2004

In [178]:
df_2004.head()

,City & State,cancer,cardiovascular,stroke,depression,rehab,vaccine,diarrhea,obesity,diabetes,year
0,Portland-Auburn ME,44,6,17,39,21,31,14,29,38,2004
1,New York NY,47,6,13,38,16,33,12,27,32,2004
2,Binghamton NY,48,3,16,50,12,37,24,31,37,2004
3,Macon GA,44,14,14,37,19,49,14,29,31,2004
4,Philadelphia PA,52,7,16,41,23,36,14,30,37,2004

In [179]:
def health_data(year):
    data = df.filter(like=year)
    data.columns = data.columns.str.replace(year,'')
    data.columns = data.columns.str.replace('+','')
    data = pd.concat([city,data],axis=1)
    data["year"] = year
    return data

In [180]:
data_2004 = health_data("2004")
data_2005 = health_data("2005")
data_2006 = health_data("2006")
data_2007 = health_data("2007")
data_2008 = health_data("2008")
data_2009 = health_data("2009")
data_2010 = health_data("2010")
data_2011 = health_data("2011")
data_2012 = health_data("2012")
data_2013 = health_data("2013")
data_2014 = health_data("2014")
data_2015 = health_data("2015")
data_2016 = health_data("2016")
data_2017 = health_data("2017")

In [181]:
data_2004.head()

,City & State,cancer,cardiovascular,stroke,depression,rehab,vaccine,diarrhea,obesity,diabetes,year
0,Portland-Auburn ME,44,6,17,39,21,31,14,29,38,2004
1,New York NY,47,6,13,38,16,33,12,27,32,2004
2,Binghamton NY,48,3,16,50,12,37,24,31,37,2004
3,Macon GA,44,14,14,37,19,49,14,29,31,2004
4,Philadelphia PA,52,7,16,41,23,36,14,30,37,2004

In [182]:
data_2009.head()

,City & State,cancer,cardiovascular,stroke,depression,rehab,vaccine,diarrhea,obesity,diabetes,year
0,Portland-Auburn ME,61,20,60,20,47,40,59,38,56,2009
1,New York NY,58,18,44,19,39,36,49,34,53,2009
2,Binghamton NY,58,19,59,25,36,43,68,54,49,2009
3,Macon GA,53,36,53,19,59,24,48,41,57,2009
4,Philadelphia PA,65,23,50,21,52,40,57,40,63,2009

In [183]:
test = pd.concat([data_2004,data_2005,data_2006,data_2007,data_2008,data_2009,data_2010,data_2011,data_2012,data_2013,data_2014,data_2015,data_2016,data_2017])
test

,City & State,cancer,cardiovascular,stroke,depression,rehab,vaccine,diarrhea,obesity,diabetes,year
0,Portland-Auburn ME,44,6,17,39,21,31,14,29,38,2004
1,New York NY,47,6,13,38,16,33,12,27,32,2004
2,Binghamton NY,48,3,16,50,12,37,24,31,37,2004
3,Macon GA,44,14,14,37,19,49,14,29,31,2004
4,Philadelphia PA,52,7,16,41,23,36,14,30,37,2004
5,Detroit MI,47,6,16,45,14,31,15,27,34,2004
6,Boston MA-Manchester NH,48,6,15,38,25,34,14,27,37,2004
7,Savannah GA,43,11,17,37,28,43,10,45,26,2004
8,Pittsburgh PA,51,10,17,50,23,34,16,35,43,2004
9,Ft. Wayne IN,42,4,14,50,15,25,15,25,36,2004
10,Cleveland-Akron (Canton) OH,42,6,16,44,18,26,14,25,36,2004
11,Washington DC (Hagerstown MD),47,5,15,33,15,46,11,31,37,2004
12,Baltimore MD,51,9,18,44,18,44,16,29,40,2004
13,Flint-Saginaw-Bay City MI,43,8,17,50,12,34,19,48,31,2004
14,Buffalo NY,49,5,20,49,18,25,16,26,37,2004
15,Cincinnati OH,45,6,18,43,17,25,15,28,39,2004
16,Erie PA,53,14,17,50,25,43,8,53,44,2004
17,Charlotte NC,43,7,16,39,21,29,16,25,35,2004
18,Greensboro-High Point-Winston Salem NC,47,10,15,45,24,29,13,32,37,2004
19,Charleston SC,55,14,20,42,16,23,15,15,42,2004
20,Augusta GA,48,12,26,39,18,24,14,33,37,2004
21,Providence RI-New Bedford MA,43,3,16,45,20,36,17,20,32,2004
22,Columbus GA,41,7,17,46,25,33,14,64,39,2004
23,Burlington VT-Plattsburgh NY,49,6,14,53,21,44,10,43,38,2004
24,Atlanta GA,42,6,15,35,19,36,13,23,36,2004
25,Albany GA,44,5,12,43,27,24,16,18,46,2004
26,Utica NY,42,19,19,63,31,100,19,49,29,2004
27,Indianapolis IN,49,10,17,47,16,31,15,38,45,2004
28,Miami-Ft. Lauderdale FL,37,7,11,29,17,28,7,20,34,2004
29,Louisville KY,49,5,13,42,25,15,11,43,39,2004
...,...,...,...,...,...,...,...,...,...,...,...
180,Rapid City SD,59,27,70,59,55,69,66,64,74,2017
181,El Paso TX,59,52,53,67,39,70,66,53,82,2017
182,Helena MT,67,10,75,64,58,91,69,46,93,2017
183,Casper-Riverton WY,59,27,93,66,42,70,75,45,80,2017
184,Salt Lake City UT,55,31,68,66,50,68,69,54,75,2017
185,Yuma AZ-El Centro CA,57,57,55,60,36,65,71,48,80,2017
186,Grand Junction-Montrose CO,57,19,74,61,43,68,66,56,72,2017
187,Tucson (Sierra Vista) AZ,65,27,64,63,49,78,73,55,79,2017
188,Albuquerque-Santa Fe NM,61,29,65,64,45,71,68,49,80,2017
189,Glendive MT,58,0,0,0,0,0,0,0,0,2017
190,Bakersfield CA,59,44,58,60,26,61,77,51,78,2017
191,Eugene OR,61,31,75,59,40,80,65,86,79,2017
192,Eureka CA,61,35,76,67,43,84,61,47,66,2017
193,Los Angeles CA,59,33,55,58,37,65,61,53,74,2017
194,Palm Springs CA,64,27,70,52,40,56,78,47,81,2017
195,San Francisco-Oakland-San Jose CA,56,29,53,52,28,69,50,45,67,2017
196,Yakima-Pasco-Richland-Kennewick WA,58,25,60,62,34,78,72,48,80,2017
197,Reno NV,59,30,69,60,43,74,68,54,69,2017
198,Medford-Klamath Falls OR,64,23,77,63,40,76,66,40,79,2017
199,Seattle-Tacoma WA,57,22,63,56,42,80,63,46,71,2017
200,Portland OR,56,31,62,58,44,67,59,58,73,2017
201,Bend OR,60,26,81,59,39,77,55,50,61,2017
202,San Diego CA,61,37,57,59,37,80,61,56,76,2017
203,Monterey-Salinas CA,57,27,55,66,28,72,51,64,67,2017
204,Las Vegas NV,59,31,55,52,52,60,65,42,70,2017
205,Santa Barbara-Santa Maria-San Luis Obispo CA,53,24,60,59,28,76,56,53,63,2017
206,Sacramento-Stockton-Modesto CA,59,29,64,55,36,75,66,55,76,2017
207,Fresno-Visalia CA,56,42,61,68,36,61,73,63,77,2017
208,Chico-Redding CA,58,38,76,63,59,89,70,62,75,2017
209,Spokane WA,63,33,77,61,43,85,75,53,73,2017

In [184]:
test.to_csv("Output/health_data.csv", index=False)